// eslint-disable-next-line import/prefer-default-export
export const tradMenu = {
  en: {
    about: 'about',
    web: 'web development',
    translation: 'translation',
    background: 'background',
    contact: 'contact',
  },
  fr: {
    about: 'à propos',
    web: 'développement web',
    translation: 'traduction',
    background: 'parcours',
    contact: 'contact',
  },
  nl: {
    about: 'over mij',
    web: 'web development',
    translation: 'vertaling',
    background: 'achtergrond',
    contact: 'contact',
  },
};

export const tradAbout = {
  en: {
    about: 'about',
    me: 'me',
    p1: 'I am a <strong>Junior Web Application Developer (Full-Stack)</strong> with an extensive background as Language Service Provider and Customer Assistant and a Master’s Degree in Conference Interpreting.',
    p2: 'Studying, working and living in four European countries helped me develop a truly global mindset, the ability to adapt and the courage to take up new challenges.',
    p3: ' After more than 7 years of professional experience as a <strong>translator, conference interpreter and language specialist</strong>, I have decided to dive into the world of programming, with a full-time Web application development training at <strong>Interface3</strong> (Brussels).',
    p4: 'I am currently looking for a <strong>6-8 weeks internship opportunity in June-July 2021</strong> to continue improving my skills.',
    contact: 'Get in touch',
  },
  fr: {
    about: 'à propos',
    me: 'de moi',
    p1: 'Je suis une <strong>Junior Web Application Developer (Full-Stack)</strong> avec une longue expérience en tant que prestataire de services linguistiques et assistante à la clientèle, avec une maîtrise en Interprétation de Conférence.',
    p2: "Avoir étudié, travaillé et habité dans quatre pays européens m'a permis de développer une véritable mentalité internationale, la capacité de m'adapter à toute situation et le courage de relever de nouveaux défis.",
    p3: "Après plus de 7 ans d'expérience professionnelle en tant que <strong>traductrice, interprète et spécialiste du language</strong>, j'ai décidé de me découvrir le monde de la programmation, avec un programme de formation à temps plein chez <strong>Interface3</strong> (Bruxelles).",
    p4: 'À présent, je cherche un <strong>stage de 6 à 8 semaines pendant les mois de juin-juillet 2021</strong> pour continuer à améliorer mes compétences dans ce domaine.',
    contact: 'contactez-moi',
  },
  nl: {
    about: 'over',
    me: 'mij',
    p1: 'Ik ben een <strong>Junior Web Application Developer (Full-Stack)</strong> met een grote ervaring als taaldienstverlener en klantenservice medevewerker, met een Masteropleiding in Conferentietolken.',
    p2: 'Dankzij mijn studie-, levens- en werkervaringen in vier Europese landen, heb ik een echte globale mentaliteit ontwikkeld, leerde ik om me makkelijk aan nieuwe situaties aan te passen en kreeg ik de moed om uitdagingen aan te gaan.',
    p3: 'Na meer dan 7 jaar professionele ervaring als<strong>vertalster, conferentietolk en taalkundig</strong>, besloot ik om de wereld van web programming te ontdekken, met een Web application development voltijdse opleiding bij <strong>Interface3</strong> (Brussel).',
    p4: 'Tegenwoordig zoek ik op een <strong>6-8 weken stage in juni-juli 2021</strong> om mijn vaardigheden te verbeteren.',
    contact: 'neem contact op',
  },
};

export const tradWeb = {
  en: {
    web: 'web',
    development: 'development',
    it: 'IT Skills',
    group: ['web', 'languages', 'frameworks', 'databases', 'analysis', 'tools', 'cms', 'servers', 'project management'],
    written: 'Written mainly in ',
  },
  fr: {
    web: 'développement',
    development: 'web',
    it: 'compétences informatiques',
    group: ['web', 'langages', 'frameworks', 'bases de données', 'analyse', 'outils', 'cms', 'serveurs', 'gestion de projets'],
    written: 'Développé principalement en ',
  },
  nl: {
    web: 'web',
    development: 'development',
    it: 'IT vaardigheden',
    group: ['web', 'programmeertalen', 'frameworks', 'databases', 'analyse', 'tools', 'cms', 'servers', 'projectbeheer'],
    written: 'Ontwikkeld met ',
  },
};

export const tradTranslation = {
  en: {
    services1: 'Language',
    services2: 'services',
    trad: 'Translation',
    tradLangs: 'English, French, Spanish, Dutch, Croatian > Italian',
    knowMore: 'Read more',
    tradSpecialisations: 'My fields of specialisation are : <br />Medical reports, IT, Business Communication, and Tourism.',
    int: 'Interpreting',
    intLangs: 'Between French, Spanish and Italian<br />From English into Italian',
    sim: '<strong>Simultaneous Interpreting</strong>',
    knowMoreSim: 'No delay between the speaker and the interpreter.<br /><br />It is performed in a booth and the public has headphones on.<br /><br />Perfect for big events, training sessions, and if the speech needs to be interpreted into more than one foreign languages.',
    cons: '<strong>Consecutive Interpreting</strong>',
    knowMoreCons: 'The speaker stops every 5-10 minutes, allowing the interpreter to repeat.<br /><br />Perfect for bilingual events, ceremonies, workshops.',
    whisp: '<strong>Whispered Interpreting</strong>',
    knowMoreWhisp: "The interpreters whispers the translation directly into the client's ear.",
    quote: 'Request a quote',
    proz: 'Check my professional page on ProZ.com',
  },

  fr: {
    services1: 'Services',
    services2: 'linguistiques',
    trad: 'Traduction',
    tradLangs: 'Anglais, français, espagnol, néerlandais, Croate > italian',
    knowMore: "Plus d'info",
    tradSpecialisations: 'Mes domaines de spécialisation sont :<br />rapports médicaux, informatique, communication commerciale et tourisme. <br /><br />',
    int: 'Interprétation',
    intLangs: "Entre français, espagnol et italien<br />De l'anglais vers l'italien.",
    sim: '<strong>Interprétation simultanée</strong>',
    knowMoreSim: 'lorem ipsum bla bla bla',
    cons: '<strong>Interprétation consécutive</strong>',
    knowMoreCons: 'lorem ipsum bla bla bla',
    whisp: '<strong>Chuchotage</strong>',
    knowMoreWhisp: 'lorem ipsum bla bla bla',
    quote: 'Demandez un devis',
    proz: 'Visitez ma page professionnelle sur ProZ.com',
  },
  nl: {
    services1: 'Taalkundige',
    services2: 'diensten',
    trad: 'Vertaling',
    tradLangs: 'Engels, Frans, Nederlands, Spaans, Kroatisch > Italiaans',
    knowMore: 'Lees meer',
    tradSpecialisations: 'Mijn specialitatiegebieden zijn:<br />medische dossiers, IT, bedrijfscommunicatie en toerisme.',
    int: 'Tolken',
    intLangs: 'Tussen Frans, Spaans en Italiaans<br />Vanuit het Engels naar het Italiaans',
    sim: '<strong>Simultaan tolken</strong>',
    knowMoreSim: 'lorem ipsum bla bla bla',
    cons: '<strong>Consecutief tolken</strong>',
    knowMoreCons: 'lorem ipsum bla bla bla',
    whisp: '<strong>Fluistertolken</strong>',
    knowMoreWhisp: 'lorem ipsum bla bla bla',
    quote: 'Een prijsopgave vragen',
    proz: 'Ga naar mijn professionele profiel op ProZ.com',
  },
};
