// eslint-disable-next-line import/prefer-default-export
export const tradHeader = {
  en: {
    web: 'Web Application Developer',
    trad: 'Translator / Interpreter',
    choose: 'Choose your language:',
  },
  fr: {
    web: "Développeuse d'applications web",
    trad: 'Traductrice / Interprète',
    choose: 'Choisissez votre langue :',
  },
  nl: {
    web: 'Web Application Developer',
    trad: 'Vertalster / Tolk',
    choose: 'Kies uw taal:',
  },
};

export const tradMenu = {
  en: {
    about: 'about',
    web: 'web development',
    translation: 'translation',
    background: 'background',
    contact: 'contact',
    cv: 'alessia_scaccia_cv_EN.pdf',
  },
  fr: {
    about: 'à propos',
    web: 'développement web',
    translation: 'traduction',
    background: 'parcours',
    contact: 'contact',
    cv: 'alessia_scaccia_cv_FR.pdf',
  },
  nl: {
    about: 'over mij',
    web: 'web development',
    translation: 'vertaling',
    background: 'achtergrond',
    contact: 'contact',
    cv: 'alessia_scaccia_cv_NL.pdf',
  },
};

export const tradAbout = {
  en: {
    about: 'about',
    me: 'me',
    p1: 'I am a <strong>Junior Web Application Developer</strong>,<br /> interpreter and translator.<br /> I live in Brussels',
    p2: 'Studying, working and living in four European countries helped me develop a truly global mindset, the ability to adapt and the courage to take up new challenges.',
    p3: ' After more than 7 years of professional experience as a <strong>translator, conference interpreter and language specialist</strong>, I have decided to dive into the world of programming, with a full-time Web application development training at <strong>Interface3</strong> (Brussels).',
    p4: 'I am currently looking for a <strong>6-8 weeks internship opportunity between May 24th and July 2nd/16th 2021</strong> to continue improving my skills.',
    contact: 'Get in touch',
  },
  fr: {
    about: 'à propos',
    me: 'de moi',
    p1: "Je suis une <strong>Junior Web Application Developer</strong>,<br /> interprète et traductrice.<br /> J'habite à Bruxelles.",
    p2: "Avoir étudié, travaillé et habité dans quatre pays européens m'a permis de développer une véritable mentalité internationale, la capacité de m'adapter à toute situation et le courage de relever de nouveaux défis.",
    p3: "Après plus de 7 ans d'expérience professionnelle en tant que <strong>traductrice, interprète et spécialiste du language</strong>, j'ai décidé de découvrir le monde de la programmation, avec un programme de formation à temps plein chez <strong>Interface3</strong> (Bruxelles).",
    p4: 'À présent, je cherche un <strong>stage de 6 à 8 semaines du 24 Mai 2021 au 2/16 Juillet 2021</strong> pour continuer à améliorer mes compétences dans ce domaine.',
    contact: 'contactez-moi',
  },
  nl: {
    about: 'over',
    me: 'mij',
    p1: 'Ik ben een <strong>Junior Web Application Developer </strong>,<br /> vertalster en tolk.<br /> Ik woon in Brussel.',
    p2: 'Dankzij mijn studie-, levens- en werkervaringen in vier Europese landen, heb ik een echte globale mentaliteit ontwikkeld, leerde ik om me makkelijk aan nieuwe situaties aan te passen en kreeg ik de moed om uitdagingen aan te gaan.',
    p3: 'Na meer dan 7 jaar professionele ervaring als <strong>vertalster, conferentietolk en taalkundig</strong>, besloot ik om de wereld van web programming te ontdekken, met een Web application development voltijdse opleiding bij <strong>Interface3</strong> (Brussel).',
    p4: 'Tegenwoordig zoek ik op een <strong>6-8 weken stage tussen 24 mei en 2/16 juli 2021</strong> om mijn vaardigheden te verbeteren.',
    contact: 'neem contact op',
  },
};

export const tradWeb = {
  en: {
    web: 'web',
    development: 'development',
    it: 'IT Skills',
    group: ['web', 'languages', 'frameworks', 'databases', 'analysis', 'tools', 'cms', 'servers', 'project management'],
    written: 'Written mainly in ',
  },
  fr: {
    web: 'développement',
    development: 'web',
    it: 'compétences informatiques',
    group: ['web', 'langages', 'frameworks', 'bases de données', 'analyse', 'outils', 'cms', 'serveurs', 'gestion de projets'],
    written: 'Développé principalement en ',
  },
  nl: {
    web: 'web',
    development: 'development',
    it: 'IT vaardigheden',
    group: ['web', 'programmeertalen', 'frameworks', 'databases', 'analyse', 'tools', 'cms', 'servers', 'projectbeheer'],
    written: 'Ontwikkeld met ',
  },
};

export const tradTranslation = {
  en: {
    services1: 'Language',
    services2: 'services',
    trad: 'Translation',
    tradLangs: 'English | French | Spanish | Dutch | Croatian',
    knowMore: 'Read more',
    tradSpecialisations: 'My fields of specialisation are : <br />Medical reports, IT, Business Communication, and Tourism.',
    tradServices: 'I perform <strong>translations, proofreading and editing tasks </strong> from all my foreign languages into Italian.',
    cat: 'CAT TOOLS used: SDL Trados, MemoQ, OmegaT',
    int: 'Interpreting',
    intLangs: 'Between French, Spanish and Italian<br />From English into Italian',
    sim: '<strong>Simultaneous Interpreting</strong>',
    knowMoreSim: 'No delay between the speaker and the interpreter.<br /><br />It is performed in a booth and the public has headphones on.<br /><br />Perfect for big events, training sessions, and if the speech needs to be interpreted into more than one foreign language.',
    cons: '<strong>Consecutive Interpreting</strong>',
    knowMoreCons: 'The speaker stops every 5-10 minutes, allowing the interpreter to repeat.<br /><br />Perfect for bilingual events, ceremonies, and workshops.',
    whisp: '<strong>Whispered Interpreting</strong>',
    knowMoreWhisp: "The interpreters whispers the translation directly into the client's ear.",
    quote: 'Request a quote',
    proz: 'Check my professional page on ProZ.com',
  },

  fr: {
    services1: 'Services',
    services2: 'linguistiques',
    trad: 'Traduction',
    tradLangs: 'anglais | français | espagnol | néerlandais | Croate',
    knowMore: "Plus d'info",
    tradSpecialisations: 'Mes domaines de spécialisation sont :<br />rapports médicaux, informatique, communication commerciale et tourisme. <br /><br />',
    tradServices: 'I perform <strong>translations, proofreading and editing tasks </strong> from all my foreign languages into Italian.',
    cat: 'CAT TOOLS used: SDL Trados, MemoQ, OmegaT',
    int: 'Interprétation',
    intLangs: "Entre français, espagnol et italien<br />De l'anglais vers l'italien",
    sim: '<strong>Interprétation simultanée</strong>',
    knowMoreSim: 'lorem ipsum bla bla bla',
    cons: '<strong>Interprétation consécutive</strong>',
    knowMoreCons: 'lorem ipsum bla bla bla',
    whisp: '<strong>Chuchotage</strong>',
    knowMoreWhisp: 'lorem ipsum bla bla bla',
    quote: 'Demandez un devis',
    proz: 'Visitez ma page professionnelle sur ProZ.com',
  },
  nl: {
    services1: 'Taalkundige',
    services2: 'diensten',
    trad: 'Vertaling',
    tradLangs: 'Engels | Frans | Nederlands | Spaans | Kroatisch',
    knowMore: 'Lees meer',
    tradSpecialisations: 'Mijn specialitatiegebieden zijn:<br />medische dossiers, IT, bedrijfscommunicatie en toerisme.',
    tradServices: 'I perform <strong>translations, proofreading and editing tasks </strong> from all my foreign languages into Italian.',
    cat: 'CAT TOOLS used: SDL Trados, MemoQ, OmegaT',
    int: 'Tolken',
    intLangs: 'Tussen Frans, Spaans en Italiaans<br />Vanuit het Engels naar het Italiaans',
    sim: '<strong>Simultaan tolken</strong>',
    knowMoreSim: 'lorem ipsum bla bla bla',
    cons: '<strong>Consecutief tolken</strong>',
    knowMoreCons: 'lorem ipsum bla bla bla',
    whisp: '<strong>Fluistertolken</strong>',
    knowMoreWhisp: 'lorem ipsum bla bla bla',
    quote: 'Een offerte vragen',
    proz: 'Bezoek mijn professionele profiel op ProZ.com',
  },
};

export const tradBackground = {
  en: {
    my: 'my',
    background: 'background',
    school: 'Finished High School in Latina, Italy.',
    startUniv: "Started my Bachelor's degree in Multilingual Communication and Translation at the <a href='https://iuslit.units.it/en' target='_blank'>University of Trieste</a>.",
    zagrebOne: 'Won a scholarship for an intensive course of Croatian at the <a href="https://croaticum.ffzg.unizg.hr/" target="_blank"> University of Zagreb</a>.',
    holland: 'Internship at <a href="https://www.bladenis.com/" target="_blank">Bladenis</a> (Amsterdam), as a translator.',
    erasmus: 'Erasmus program at EII, <a href="https://web.umons.ac.be/fti-eii/en/" target="_blank">University of Mons</a>.',
    startTrad: 'Started volunteering and performing my first translations assignments.',
    laureaT: 'Obtained my BA with honors.',
    toBcn: 'Moved to Barcelona.',
    eugin: 'Started at <a href="https://www.eugin.co.uk/" target="_blank">Clinica Eugin</a> as a multilingual medical assistant.',
    officialTrad: 'Also worked as an interpreter for the police department.',
    master: "Admitted to the Master's Degree in Conference Interpreting at the University of Trieste.",
    zagrebTwo: 'Moved to Zagreb again to continue studying Croatian and writing my thesis.',
    agape: 'Joined the no profit organization <a href="https://agapecentroecumenico.org/en/" target="_blank">Agape Centro Ecumenico</a> as a volunteer interpreter.',
    laureaM: 'Obtained my MA in Interpreting.',
    toBxl: 'Moved to Brussels.',
    capstan: 'Internship as a Translation Project Manager at <a href="https://www.capstan.be/" target="_blank">cApStAn</a>.',
    lv: 'Seasonal work as Multilingual Client Advisor for  <a href="https://en.louisvuitton.com/eng-nl/homepage?dispatchCountry=BE" target="_blank">LVMH</a>.',
    cigna: 'Joined <a href="https://www.cignahealthbenefits.com/en/" target="_blank">Cigna</a> as a Provider Relations Manager (responsible for Italy, Switzerland, France, Kenya, and South Africa).',
    pm: 'Left Cigna and started working as a Project Management Consultant for Translation projects.',
    omi: 'Discovered web developement with a Wordpress course at <a href="https://molengeek.com/" target="_blank">Molengeek</a> and with an orientation program at <a href="https://www.interface3.be/" target="_blank">Interface3</a>.',
    wad: 'Entered the Web Application Development program at Interface3.',
    endWad: 'Will conclude the Web Application Development program and be ready for an intership opportunity.',
    job: '...and hopefully get my first job as a developer?',
  },
  fr: {
    my: 'mon',
    background: 'parcours',
    school: 'Finished High School in Latina, Italy.',
    startUniv: "Started my Bachelor's degree in Multilingual Communication and Translation at the <a href='https://iuslit.units.it/en' target='_blank'>University of Trieste</a>.",
    zagrebOne: 'Won a scholarship for an intensive course of Croatian at the University of Zagreb.',
    holland: 'Internship at <a href="https://www.bladenis.com/" target="_blank">Bladenis</a> (Amsterdam), as a translator.',
    erasmus: 'Erasmus program at EII, <a href="https://web.umons.ac.be/fti-eii/en/" target="_blank">University of Mons</a>.',
    startTrad: 'Started volunteering and performing my first translations assignments.',
    laureaT: 'Obtained my BA with honors.',
    toBcn: 'Moved to Barcelona.',
    eugin: 'Started at <a href="https://www.eugin.co.uk/" target="_blank">Clinica Eugin</a> as a multilingual medical assistant.',
    officialTrad: 'Also worked as an interpreter for the police department.',
    master: "Admitted to the Master's Degree in Conference Interpreting at the University of Trieste.",
    zagrebTwo: 'Moved to Zagreb again to continue studying Croatian and writing my thesis.',
    agape: 'Joined the no profit organization <a href="https://agapecentroecumenico.org/en/" target="_blank">Agape Centro Ecumenico</a> as a volunteer interpreter.',
    laureaM: 'Obtained my MA in Interpreting.',
    toBxl: 'Moved to Brussels.',
    capstan: 'Internship as a Translation Project Manager at <a href="https://www.capstan.be/" target="_blank">cApStAn</a>.',
    lv: 'Seasonal work as Multilingual Client Advisor for LVMH <a href="https://en.louisvuitton.com/eng-nl/homepage?dispatchCountry=BE" target="_blank">/ Louis Vuitton</a>.',
    cigna: 'Joined <a href="https://www.cignahealthbenefits.com/en/" target="_blank">Cigna</a> as a Provider Relations Manager (responsible for Italy, Switzerland, France, Kenya, and South Africa).',
    pm: 'Left Cigna and started working as a Project Management Consultant.',
    omi: 'Discovered web developement with a Wordpress course at <a href="https://molengeek.com/" target="_blank">Molengeek</a> and with an orientation program at <a href="https://www.interface3.be/" target="_blank">Interface3</a>.',
    wad: 'Entered the Web Application Development program at Interface3.',
    endWad: 'Will conclude the Web Application Development program and be ready for an intership opportunity.',
    job: '...and hopefully get my first job as a developer?',
  },
  nl: {
    my: 'mijn',
    background: 'achtergrond',
    school: 'Finished High School in Latina, Italy.',
    startUniv: "Started my Bachelor's degree in Multilingual Communication and Translation at the <a href='https://iuslit.units.it/en' target='_blank'>University of Trieste</a>.",
    zagrebOne: 'Won a scholarship for an intensive course of Croatian at the University of Zagreb.',
    holland: 'Internship at <a href="https://www.bladenis.com/" target="_blank">Bladenis</a> (Amsterdam), as a translator.',
    erasmus: 'Erasmus program at EII, <a href="https://web.umons.ac.be/fti-eii/en/" target="_blank">University of Mons</a>.',
    startTrad: 'Started volunteering and performing my first translations assignments.',
    laureaT: 'Obtained my BA with honors.',
    toBcn: 'Moved to Barcelona.',
    eugin: 'Started at <a href="https://www.eugin.co.uk/" target="_blank">Clinica Eugin</a> as a multilingual medical assistant.',
    officialTrad: 'Also worked as an interpreter for the police department.',
    master: "Admitted to the Master's Degree in Conference Interpreting at the University of Trieste.",
    zagrebTwo: 'Moved to Zagreb again to continue studying Croatian and writing my thesis.',
    agape: 'Joined the no profit organization <a href="https://agapecentroecumenico.org/en/" target="_blank">Agape Centro Ecumenico</a> as a volunteer interpreter.',
    laureaM: 'Obtained my MA in Interpreting.',
    toBxl: 'Moved to Brussels.',
    capstan: 'Internship as a Translation Project Manager at <a href="https://www.capstan.be/" target="_blank">cApStAn</a>.',
    lv: 'Seasonal work as Multilingual Client Advisor for LVMH <a href="https://en.louisvuitton.com/eng-nl/homepage?dispatchCountry=BE" target="_blank">/ Louis Vuitton</a>.',
    cigna: 'Joined <a href="https://www.cignahealthbenefits.com/en/" target="_blank">Cigna</a> as a Provider Relations Manager (responsible for Italy, Switzerland, France, Kenya, and South Africa).',
    pm: 'Left Cigna and started working as a Project Management Consultant.',
    omi: 'Discovered web developement with a Wordpress course at <a href="https://molengeek.com/" target="_blank">Molengeek</a> and with an orientation program at <a href="https://www.interface3.be/" target="_blank">Interface3</a>.',
    wad: 'Entered the Web Application Development program at Interface3.',
    endWad: 'Will conclude the Web Application Development program and be ready for an intership opportunity.',
    job: '...and hopefully get my first job as a developer?',
  },
};

export const tradContact = {
  en: {
    contact: 'contact',
    me: 'me',
    placeholderName: 'Your name',
    placeholderEmail: 'Your email',
    placeholderMsg: 'Your message',
    send: 'Send',
    msgOk: 'Thank you for your message',
  },
  fr: {
    contact: 'contactez',
    me: 'moi',
    placeholderName: 'Votre nom',
    placeholderEmail: 'Votre email',
    placeholderMsg: 'Votre message',
    send: 'Envoyer',
    msgOk: 'Merci de votre message',
  },
  nl: {
    contact: 'contacteer',
    me: 'me',
    placeholderName: 'Uw naam',
    placeholderEmail: 'Uw email',
    placeholderMsg: 'Uw bericht',
    send: 'Versturen',
    msgOk: 'Bedankt voor uw bericht',
  },
};
