// eslint-disable-next-line import/prefer-default-export
export const tradHeader = {
  en: {
    web: 'Web Application Developer',
    trad: 'Translator / Interpreter',
    choose: 'Choose your language:',
  },
  fr: {
    web: "Développeuse d'applications web",
    trad: 'Traductrice / Interprète',
    choose: 'Choisissez votre langue :',
  },
  nl: {
    web: 'Web Application Developer',
    trad: 'Vertalster / Tolk',
    choose: 'Kies uw taal:',
  },
};

export const tradMenu = {
  en: {
    about: 'about',
    web: 'web',
    translation: 'translation',
    background: 'background',
    contact: 'contact',
    cv: 'alessia_scaccia_cv_EN.pdf',
  },
  fr: {
    about: 'à propos',
    web: 'web',
    translation: 'traduction',
    background: 'parcours',
    contact: 'contact',
    cv: 'alessia_scaccia_cv_FR.pdf',
  },
  nl: {
    about: 'over mij',
    web: 'web',
    translation: 'vertaling',
    background: 'achtergrond',
    contact: 'contact',
    cv: 'alessia_scaccia_cv_NL.pdf',
  },
};

export const tradAbout = {
  en: {
    about: 'about',
    me: 'me',
    p1: 'I am a <strong>Junior Web Application Developer</strong>,<br /> interpreter and translator.<br /> I live in Brussels',
    p2: 'Studying, working and living in four European countries helped me develop a truly global mindset, the ability to adapt and the courage to take up new challenges.',
    p3: ' After more than 7 years of professional experience as a <strong>translator, conference interpreter and language specialist</strong>, I decided to dive into the world of programming, with a full-time Web application development training at <strong>Interface3</strong> (Brussels).',
    p4: 'I am currently looking for a <strong>6-8 week internship opportunity between May 24th and July 2nd/16th 2021</strong> to continue improving my skills.',
    contact: 'Get in touch',
  },
  fr: {
    about: 'à propos',
    me: 'de moi',
    p1: "Je suis une <strong>Junior Web Application Developer</strong>,<br /> interprète et traductrice.<br /> J'habite à Bruxelles.",
    p2: "Avoir étudié, travaillé et habité dans quatre pays européens m'a permis de développer une véritable mentalité internationale, la capacité de m'adapter à toute situation et le courage de relever de nouveaux défis.",
    p3: "Après plus de 7 ans d'expérience professionnelle en tant que <strong>traductrice, interprète et spécialiste du language</strong>, j'ai décidé de découvrir le monde de la programmation, avec un programme de formation à temps plein chez <strong>Interface3</strong> (Bruxelles).",
    p4: 'À présent, je cherche un <strong>stage de 6 à 8 semaines du 24 Mai 2021 au 2/16 Juillet 2021</strong> pour continuer à améliorer mes compétences dans ce domaine.',
    contact: 'contactez-moi',
  },
  nl: {
    about: 'over',
    me: 'mij',
    p1: 'Ik ben een <strong>Junior Web Application Developer </strong><br /> vertalster en tolk.<br /> Ik woon in Brussel.',
    p2: 'Dankzij mijn studie-, levens- en werkervaringen in vier Europese landen, heb ik een echte globale mentaliteit ontwikkeld, leerde ik om me makkelijk aan nieuwe situaties aan te passen en kreeg ik de moed om uitdagingen aan te gaan.',
    p3: 'Na meer dan 7 jaar professionele ervaring als <strong>vertalster, conferentietolk en taalkundig</strong>, besloot ik om de wereld van web programming te ontdekken, met een Web application development voltijdse opleiding bij <strong>Interface3</strong> (Brussel).',
    p4: 'Tegenwoordig zoek ik op een <strong>6-8 weken stage tussen 24 mei en 2/16 juli 2021</strong> om mijn vaardigheden te verbeteren.',
    contact: 'neem contact op',
  },
};

export const tradWeb = {
  en: {
    web: 'web',
    development: 'development',
    it: 'IT Skills',
    group: ['web', 'languages', 'frameworks', 'databases', 'analysis', 'tools', 'cms', 'servers', 'project management'],
    written: 'Written mainly in ',
  },
  fr: {
    web: 'développement',
    development: 'web',
    it: 'compétences informatiques',
    group: ['web', 'langages', 'frameworks', 'bases de données', 'analyse', 'outils', 'cms', 'serveurs', 'gestion de projets'],
    written: 'Développé principalement en ',
  },
  nl: {
    web: 'web',
    development: 'development',
    it: 'IT vaardigheden',
    group: ['web', 'programmeertalen', 'frameworks', 'databases', 'analyse', 'tools', 'cms', 'servers', 'projectbeheer'],
    written: 'Ontwikkeld met ',
  },
};

export const tradTranslation = {
  en: {
    services1: 'Language',
    services2: 'services',
    trad: 'Translation',
    tradLangs: 'English | French | Spanish | Dutch | Croatian',
    knowMore: 'Read more',
    tradSpecialisations: 'My fields of specialisation are : <br />Medical reports, IT, Business Communication, and Tourism.',
    tradServices: 'I <strong>translate, proofread and edit</strong> from all my foreign languages into Italian.',
    cat: 'CAT TOOLS used: SDL Trados, MemoQ, OmegaT',
    int: 'Interpreting',
    intLangs: 'Between French, Spanish and Italian<br />From English into Italian',
    sim: '<strong>Simultaneous Interpreting</strong>',
    knowMoreSim: 'No delay between the speaker and the interpreter.<br /><br />It is performed in a booth and the public wears headphones.<br /><br />Perfect for big events, training sessions, and if the speech needs to be interpreted into more than one foreign language.',
    cons: '<strong>Consecutive Interpreting</strong>',
    knowMoreCons: 'The speaker stops/pauses every 5-10 minutes, allowing the interpreter to translate the speech in the target language.<br /><br />Perfect for bilingual events, ceremonies, and workshops.',
    whisp: '<strong>Whispered Interpreting</strong>',
    knowMoreWhisp: "The interpreter whispers the translation directly into the client's ear.<br /><br />It's the perfect technique when only 1-2 participants don't speak the meeting's language.",
    quote: 'Request a quote',
    proz: 'Check my professional page on ProZ.com',
  },

  fr: {
    services1: 'Services',
    services2: 'linguistiques',
    trad: 'Traduction',
    tradLangs: 'anglais | français | espagnol | néerlandais | Croate',
    knowMore: "Plus d'info",
    tradSpecialisations: 'Mes domaines de spécialisation sont :<br />rapports médicaux, informatique, communication commerciale et tourisme. <br /><br />',
    tradServices: 'I perform <strong>translations, proofreading and editing tasks </strong> from all my foreign languages into Italian.',
    cat: 'CAT TOOLS used: SDL Trados, MemoQ, OmegaT',
    int: 'Interprétation',
    intLangs: "Entre français, espagnol et italien<br />De l'anglais vers l'italien",
    sim: '<strong>Interprétation simultanée</strong>',
    knowMoreSim: "L'interprète traduit le discours à mesure qu’il se déroule.<br /><br />L’interprète, installé dans une cabine insonorisée, entend au moyen d’un casque un discours qu’il traduit en temps réel. Ses auditeurs l’entendent par le biais d’oreillettes.<br /><br />Privilegiée lors d'événements avec un grand nombre de participants, pour des sessions de coatching/workshops et quand le discours doit être traduit en plusieurs langues en même temps.",
    cons: '<strong>Interprétation consécutive</strong>',
    knowMoreCons: 'L’orateur s’exprime durant 5-10 minutes, l’interprète l’écoute, prend des notes et restitue ensuite le discours dans la langue cible.<br /><br />Technique à privilegier pour les événements bilingues, les cérémonies et le présentations.',
    whisp: '<strong>Chuchotage</strong>',
    knowMoreWhisp: "L'interprète chuchote la traduction du discours en temps réel directement à l'oreille du client.<br /><br />À utiliser seulement quand 1 ou 2 participants ne parlent par la langue de la réunion.",
    quote: 'Demandez un devis',
    proz: 'Visitez ma page professionnelle sur ProZ.com',
  },
  nl: {
    services1: 'Taalkundige',
    services2: 'diensten',
    trad: 'Vertaling',
    tradLangs: 'Engels | Frans | Nederlands | Spaans | Kroatisch',
    knowMore: 'Lees meer',
    tradSpecialisations: 'Mijn specialitatiegebieden zijn:<br />medische dossiers, IT, bedrijfscommunicatie en toerisme.',
    tradServices: 'I perform <strong>translations, proofreading and editing tasks </strong> from all my foreign languages into Italian.',
    cat: 'CAT TOOLS used: SDL Trados, MemoQ, OmegaT',
    int: 'Tolken',
    intLangs: 'Tussen Frans, Spaans en Italiaans<br />Vanuit het Engels naar het Italiaans',
    sim: '<strong>Simultaan tolken</strong>',
    knowMoreSim: 'De tolk hoort de spreker via een hoofdtelefoon en vertaalt tegelijkertijd in een microfoon. De ontvangers luisteren via een ontvanger en hoofdtelefoon naar de vertaling.<br /><br />Deze techniek is geschikt voor conferenties met veel deelnemers, opleidingen, coachings en alle vergadering waar meer dan 2 talen zijn gebruikt.',
    cons: '<strong>Consecutief tolken</strong>',
    knowMoreCons: 'Eerst de spreker spreekt en steeds even stopt met praten om de tolk in de gelegenheid te stellen zijn woorden te tolken. <br /><br />Deze techniek is geschikt voor sociale- en bedrijfsevenementen, ceremonies en workshops.',
    whisp: '<strong>Fluistertolken</strong>',
    knowMoreWhisp: 'Fluistertolken houdt in dat de tolk bij de luisteraars gaat zitten en hen letterlijk de vertolking toefluistert. <br /><br />Een fluistertolk kan maximaal voor twee deelnemers tolken.',
    quote: 'Een offerte vragen',
    proz: 'Bezoek mijn professionele profiel op ProZ.com',
  },
};

export const tradBackground = {
  en: {
    my: 'my',
    background: 'background',
    school: 'Finished High School in Latina, Italy.',
    startUniv: "Started my Bachelor's degree in Multilingual Communication and Translation at the <a href='https://iuslit.units.it/en' target='_blank'>University of Trieste</a>.",
    zagrebOne: 'Won a scholarship for an intensive course in Croatian at the <a href="https://croaticum.ffzg.unizg.hr/" target="_blank"> University of Zagreb</a>.',
    holland: 'Internship at <a href="https://www.bladenis.com/" target="_blank">Bladenis</a> (Amsterdam), as a translator.',
    erasmus: 'Erasmus program at EII, <a href="https://web.umons.ac.be/fti-eii/en/" target="_blank">University of Mons</a>.',
    startTrad: 'Started performing my first translation assignments.',
    laureaT: 'Obtained my BA with honors.',
    toBcn: 'Moved to Barcelona.',
    eugin: 'Started at <a href="https://www.eugin.co.uk/" target="_blank">Clinica Eugin</a> as a multilingual medical assistant.',
    officialTrad: 'Also worked as an interpreter for the police department.',
    master: "Admitted to the Master's Degree in Conference Interpreting at the University of Trieste.",
    zagrebTwo: 'Moved to Zagreb again to continue studying Croatian and writing my thesis.',
    agape: 'Joined the non profit organization <a href="https://agapecentroecumenico.org/en/" target="_blank">Agape Centro Ecumenico</a> as a volunteer interpreter.',
    laureaM: 'Obtained my MA in Interpreting.',
    toBxl: 'Moved to Brussels.',
    capstan: 'Internship as a Translation Project Manager at <a href="https://www.capstan.be/" target="_blank">cApStAn</a>.',
    lv: 'Seasonal work as Multilingual Client Advisor for  <a href="https://en.louisvuitton.com/eng-nl/homepage?dispatchCountry=BE" target="_blank">LVMH</a>.',
    cigna: 'Joined <a href="https://www.cignahealthbenefits.com/en/" target="_blank">Cigna</a> as a Provider Relations Manager (responsible for Italy, Switzerland, France, Kenya, and South Africa).',
    pm: 'Left Cigna and started working as a Project Management Consultant for Translation projects.',
    omi: 'Discovered web developement with a Wordpress course at <a href="https://molengeek.com/" target="_blank">Molengeek</a> and with an orientation program at <a href="https://www.interface3.be/" target="_blank">Interface3</a>.',
    wad: 'Entered the Web Application Development program at Interface3.',
    endWad: 'Will conclude the Web Application Development program and be ready for an internship opportunity.',
    job: '...and hopefully get my first job as a developer!',
  },
  fr: {
    my: 'mon',
    background: 'parcours',
    school: 'Diplôme au Lycée (humanités) à Latina, Italie.',
    startUniv: "Début du Bachelier près l'<a href='https://iuslit.units.it/en' target='_blank'>Université de Trieste</a>.",
    zagrebOne: "Je reçois une bourse d'étude pour un cours intensif de croate à l'<a href='https://croaticum.ffzg.unizg.hr/' target='_blank'>Université de Zagreb</a>.",
    holland: 'Stage en traduction près de <a href="https://www.bladenis.com/" target="_blank">Bladenis</a> (Amsterdam).',
    erasmus: "Semestre Erasmus à l'EII, <a href='https://web.umons.ac.be/fti-eii/en/' target='_blank'>University of Mons</a>.",
    startTrad: 'Je commence mon activité de traductrice indépendante',
    laureaT: "J'obtiens mon diplôme de bachelier avec la plus grande distinction.",
    toBcn: 'Démenagement à Barcelone.',
    eugin: "Je travaille chez <a href='https://www.eugin.co.uk/' target='_blank'>Clinica Eugin</a> en tant qu'assistante médicale multilingues.",
    officialTrad: 'Interprète pour la police locale de Barcelone.',
    master: "Je suis admise à la maîtrise en Inteprétation de Conférences à l'Université de Trieste.",
    zagrebTwo: 'Encore un semestre à Zagreb pour approfondir la langue croate et écrire mon mémoire de maîtrise.',
    agape: "Je commence mon activité d'interprète bénévole pour <a href='https://agapecentroecumenico.org/en/' target='_blank'>Agape Centro Ecumenico</a>.",
    laureaM: "J'obtiens ma maîtrise en Interprétation de Conférences.",
    toBxl: 'Démenagement à Bruxelles.',
    capstan: 'Stage en Gestion de Projets de traduction près de <a href="https://www.capstan.be/" target="_blank">cApStAn</a>.',
    lv: 'Multilingual Client Advisor pour <a href="https://en.louisvuitton.com/eng-nl/homepage?dispatchCountry=BE" target="_blank">LVMH</a>.',
    cigna: 'Provider Relations Manager pour <a href="https://www.cignahealthbenefits.com/en/" target="_blank">Cigna</a> (responsable pour le réseau sanitaire en Italie, Suisse, France, Kenya et Afrique du Sud).',
    pm: 'Je quitte Cigna et commence à travailler comme Gestionnaire de projets de traduction.',
    omi: "Je découvre le développement web grâce à un cours de Wordpress chez <a href='https://molengeek.com/' target='_blank'>Molengeek</a> et au programme d'orientation chez <a href='https://www.interface3.be/' target='_blank'>Interface3</a>.",
    wad: 'Commence le programme en Web Application Development chez Interface3.',
    endWad: 'Je terminerai la formation et obtiendrai un stage...',
    job: '...et si tout va bien, mon premier job en tant que développeuse !',
  },
  nl: {
    my: 'mijn',
    background: 'achtergrond',
    school: 'Ik haal mijn middelbare schooldiploma (Latina, Italië).',
    startUniv: "Begin van mijn Bachelor in Vertaling en Meertalige Communicatie aan de <a href='https://iuslit.units.it/en' target='_blank'>Universiteit van Triëste</a>.",
    zagrebOne: "Ik krijg een studiebeurs voor een intensieve cursus Kroatisch aan de <a href='https://croaticum.ffzg.unizg.hr/' target='_blank'>Universiteit van Zagreb</a>.",
    holland: 'Stage bij <a href="https://www.bladenis.com/" target="_blank">Bladenis</a> (Amsterdam) als vertaler.',
    erasmus: 'Erasmus aan de <a href="https://web.umons.ac.be/fti-eii/en/" target="_blank">Universiteit van Mons</a>.',
    startTrad: 'Eerste vertaalprojecten als freelancer.',
    laureaT: 'Cum laude afgestudeerd in mijn Bachelor.',
    toBcn: 'Ik verhuis naar Barcelone.',
    eugin: 'Ik werk als Multilingual Patient Assistant bij <a href="https://www.eugin.co.uk/" target="_blank">Clinica Eugin</a>.',
    officialTrad: 'Ik werk ook als tolk voor de locale politie.',
    master: "Toegelaten tot de Master's in Conferentietolk aan de Universiteit van Trieste.",
    zagrebTwo: 'Nog een semester studie in Kroatië.',
    agape: 'Ik word vrijwilliger tolk voor <a href="https://agapecentroecumenico.org/en/" target="_blank">Agape Centro Ecumenico</a>.',
    laureaM: 'Afgestudeerd in Conferentietolk.',
    toBxl: 'Ik verhuis naar Brussel.',
    capstan: 'Stage in vertaling projectbeheer bij <a href="https://www.capstan.be/" target="_blank">cApStAn</a>.',
    lv: "Multilingual Client Advisor voor <a href='https://en.louisvuitton.com/eng-nl/homepage?dispatchCountry=BE' target='_blank'>LVMH</a>.",
    cigna: 'Ik werk voor <a href="https://www.cignahealthbenefits.com/en/" target="_blank">Cigna</a> als Provider Relations Manager (verantwoordelijk voor Italië, Zwitserland, Frankrijk, Kenia en Zuid-Afrika).',
    pm: 'Ik begin te werken als Consultant in Vertaling projectbeheer.',
    omi: 'Dankzij een Wordpress cursus bij <a href="https://molengeek.com/" target="_blank">Molengeek</a> en de oriëntatiecursus Informatica bij <a href="https://www.interface3.be/" target="_blank">Interface3</a>, ontdek ik de wereld van web programming.',
    wad: 'Ik ben toegelaten aan de Web Application Development opleiding bij Interface3.',
    endWad: 'Ik zal mijn program afmaken en een stage lopen...',
    job: '...en hopelijk zal ik mijn eerste job als web developer vinden!',
  },
};

export const tradContact = {
  en: {
    contact: 'contact',
    me: 'me',
    placeholderName: 'Your name',
    placeholderEmail: 'Your email',
    placeholderMsg: 'Your message',
    send: 'Send',
    msgOk: 'Thank you for your message',
  },
  fr: {
    contact: 'contactez',
    me: 'moi',
    placeholderName: 'Votre nom',
    placeholderEmail: 'Votre email',
    placeholderMsg: 'Votre message',
    send: 'Envoyer',
    msgOk: 'Merci de votre message',
  },
  nl: {
    contact: 'contacteer',
    me: 'me',
    placeholderName: 'Uw naam',
    placeholderEmail: 'Uw email',
    placeholderMsg: 'Uw bericht',
    send: 'Versturen',
    msgOk: 'Bedankt voor uw bericht',
  },
};
